### ISSUE TITLE
VM cannot run rosehip.iso

### ISSUE THREAD

**Issue by nehol** [donno2048/CITUR-L#6]
When I tried to use rosehip.iso I got this error:
<img width="218" alt="Annotation 2020-08-24 145721" src="https://user-images.githubusercontent.com/70110929/91042279-2c00a780-e61a-11ea-804e-29c9a5baee53.png">

**Comment by donno2048** [comment]
Try open PowerShell as administrator and pass the command: `bcdedit /set hypervisorlaunchtype off` and reboot your computer

Taken from [here](https://stackoverflow.com/questions/61344675)
